<div class="slider">
    <div class="l-container scrolled">
        <div class="g-row slider__row">
            <div class="g-column-12 slider__slides scrolled__item">
                <ul class="slider__slides__list ">
                    <li class="slider__slides__list__item current">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h2><span>Développement web</span></h2>
                        </div>
                        <figure class="slider__slides__list__item__figure">
                            <img src="images/src/home-slide.jpg" alt=""/>
                        </figure>
                    </li>
                    <!-- slider__slides__list__item -->
                    <li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h2><span>Your Portfolio. Your Style</span></h2>
                        </div>
                        <figure class="slider__slides__list__item__figure">
                            <img src="images/src/home-slide-2.jpg" alt=""/>
                        </figure>
                    </li>
                    <!-- slider__slides__list__item -->
                    <li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h2><span>Awesome ;)</span></h2>
                        </div>
                        <figure class="slider__slides__list__item__figure">
                            <img src="images/src/home-slide-3.jpg" alt=""/>
                        </figure>
                    </li>
                    <!-- slider__slides__list__item -->
                </ul>
                <!-- slider__slides__list -->
            </div>
            <!-- slider__slides -->
            <div class="g-column-12 slider__thumbs">
                <ul class="slider__thumbs__list">
                    <li class="slider__thumbs__list__item active">
                        <span>1</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>2</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>3</span>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <!-- slider -->
	
	
<div class="page">
  <div class="page__item projects scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 heading-title">
                <div>
                    <h1>Devma</h1>
                    <h3>Nous sommes une équipe de professionnels créatifs travaillant avec vous, afin de vous garantir un système de gestion meilleur.</h3>
					<p>Dans un environnement économique en mutation, les entreprises font face à des difficultés de gestion de l'information. 
					De ce fait, DEVMA est au service de la réussite de ses clients de façon à faciliter les tâches et la gestion quotidienne.
					</p>
                    <p>
                        En effet, nous proposons des services visant l'augmentation de la productivité de l'entreprise et la pérennité de son patrimoine et cela
					en vous assistant de façon à bien gérer votre société et chercher comment attirer et satisfaire votre clientèle en mettant à votre
					disponibilité tout notre savoir-faire dans le domaine.
                    </p>
                </div>
            </div>
            <!-- heading-title -->
        </div>
        
    </div>
</div>
	<div class="page__item services scrolled">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Stratégie et Création Publicitaire</h3>
                        <p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
				<div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service1.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Création et Réferencement des Sites Web</h3>
                        <p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
                <div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service2.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Développement de Logiciel et Progiciel</h3>
                        <p>Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
				<div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Gestion Financière Informatisée</h3>
                        <p>Les entreprises font face à des contraintes et à des difficultés qui peuvent présenter des risques importants...</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
 
 <!-- services -->
 <div class="page__item twitter scrolled">
    <div class="l-container">
        <div class="g-row scrolled__item">
            <div class="g-column-8 g-offset-2 twitter__content">
                <a href="index-2.html#">
                    <span class="icon_get_twitter-alt">Twitter</span>
                </a>
                <div class="twitter__container">
                    <h3>@rpauldesign cheers - hopefully it gets across we like to have fun when we work. </h3>
                </div>

            </div>
            <div class="g-column-8 g-offset-2 twitter__follow">
                <p>You should follow us on <a href="index-2.html#">Twitter</a> for our latest updates.</p>
            </div>
        </div>
    </div>
</div>
<!-- twitter -->
<div class="page__item newsletter scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 g-offset-2 scrolled__item">
                <h3>Enter your email address below to receive occasional updates.</h3>
                <form method="post" action="#">
                    <input class="input" type="email" placeholder="Enter your email" name="email">
                    <button type="submit" class="button">
                        <i class="icon icon_get_arrow-size-big">Subscribe</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- newsletter -->    </div>
<!-- page -->