<div class="slider">
    <div class="l-container scrolled">
        <div class="g-row slider__row">
            <div class="g-column-12 slider__slides scrolled__item">
                <ul class="slider__slides__list ">
                    <li class="slider__slides__list__item current">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h2><span>Devma</span></h2>
							<h4>équipe innovante et expérimentée, organisation performante...</h4>
                        </div>
                        <figure class="slider__slides__list__item__figure img-first-slide">
                            <img src="images/src/home-slide.jpg" alt=""/>
                        </figure>
                    </li>
                    <!-- slider__slides__list__item -->
                   <li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h4><span>Création et Réferencement des Sites Web</span></h4>
                        </div>
                        <figure class="slider__slides__list__item__figure img-second-slide">
                            <img src="images/src/home-slide-2.jpg" alt=""/>
                        </figure>
                    </li>
                    <!-- slider__slides__list__item -->
                    <li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description">
                            <h4><span>Management Financier Informatisé des Entreprises</span></h4>
                        </div>
                        <figure class="slider__slides__list__item__figure">
                            <img src="images/src/home-slide-3.jpg" alt=""/>
                        </figure>
                    </li>  
                    <!-- slider__slides__list__item -->
					 <li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description ">
                            <h4><span>Développement de Logiciel et Progiciel</span></h4>
                        </div>
                        <figure class="slider__slides__list__item__figure img-fourth-slide">
                            <img src="images/src/home-slide-4.jpg" alt=""/>
                        </figure>
                    </li>
					<!-- slider__slides__list__item -->
					<li class="slider__slides__list__item">
                        <div class="g-push-to-center slider__slides__list__item__description ">
                            <h4><span>Stratégie et Création Publicitaire</span></h4>
                        </div>
                        <figure class="slider__slides__list__item__figure img-fourth-slide">
                            <img src="images/src/home-slide-5.jpg" alt=""/>
                        </figure>
                    </li> 	
                    <!-- slider__slides__list__item -->
                </ul>
                <!-- slider__slides__list -->
            </div>
            <!-- slider__slides -->
            <div class="g-column-12 slider__thumbs">
                <ul class="slider__thumbs__list">
                    <li class="slider__thumbs__list__item active">
                        <span>1</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>2</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>3</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>4</span>
                    </li>
                    <li class="slider__thumbs__list__item">
                        <span>5</span>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <!-- slider -->
	
	
<div class="page">
  <div class="page__item projects scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-10 g-offset-1 heading-title">
                <div>
                    <h1>Devma</h1>
                    <h3>Nous sommes une équipe de professionnels créatifs travaillant avec vous, afin de vous garantir un système de gestion meilleur.</h3>
					<p class="bg-text">Dans un environnement économique en mutation, les entreprises font face à des difficultés de gestion de l'information. 
					De ce fait, DEVMA est au service de la réussite de ses clients de façon à faciliter les tâches et la gestion quotidienne.
					</p>
                    <p class="bg-text">
                        En effet, nous proposons des services visant l'augmentation de la productivité de l'entreprise et la pérennité de son patrimoine et cela
					en vous assistant de façon à bien gérer votre société et chercher comment attirer et satisfaire votre clientèle en mettant à votre
					disponibilité tout notre savoir-faire dans le domaine.
                    </p>
                </div>
            </div>
            <!-- <div class="g-column-3 heading-title">
                <div>
                    <img src="images/src/enjoy-working.png" alt=""/>
                </div>
            </div>
            heading-title -->
        </div>
        
    </div>
</div>
	<div class="page__item services scrolled">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service3.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Stratégie et Création Publicitaire</h3>
                        <p>Créatif en communication graphique par excellence, Réactive et créative par essence, nous sommes curieux...</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
				<div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service1.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Création et Réferencement des Sites Web</h3>
                        <p>Vous êtes-vous déjà dit: “si seulement nous avions l’application qui pouvait…”? Peut-êtes rêvez-vous d’un portail de service...</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
                <div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service2.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Développement de Logiciel et Progiciel</h3>
                        <p>Chez DEVMA, nous considérons la technologie comme un outil et non comme une fin en soi. Notre approche est donc basée sur...</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
				<div class="g-column-3 services__item scrolled__item">
                    <div class="services__item__figure">
                        <img src="images/src/service.png" alt=""/>
                    </div>
                    <div class="services__item__content">
                        <h3>Gestion Financière Informatisée</h3>
                        <p>Les entreprises font face à des contraintes et à des difficultés qui peuvent présenter des risques importants...</p>
                    </div>
                    <div class="services__item__controls">
                        <a class="button" href="index.html#">+</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
 
 <!-- services -->
 <div class="page__item twitter scrolled">
    <div class="l-container">
        <div class="g-row scrolled__item">
            <div class="g-column-8 g-offset-2 twitter__content">
                <a href="index-2.html#">
                    <span class="icon_get_twitter-alt">Twitter</span>
                </a>
                <div class="twitter__container">
                    <h3>@rpauldesign cheers - hopefully it gets across we like to have fun when we work. </h3>
                </div>

            </div>
            <div class="g-column-8 g-offset-2 twitter__follow">
                <p>You should follow us on <a href="index-2.html#">Twitter</a> for our latest updates.</p>
            </div>
        </div>
    </div>
</div>
<!-- twitter -->
<div class="page__item newsletter scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 g-offset-2 scrolled__item">
                <h3>Enter your email address below to receive occasional updates.</h3>
                <form method="post" action="#">
                    <input class="input" type="email" placeholder="Enter your email" name="email">
                    <button type="submit" class="button">
                        <i class="icon icon_get_arrow-size-big">Subscribe</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- newsletter -->    </div>
<!-- page -->