<!-- Services Fixed Toggle -->
<div class="services-toggle" >
	<div>
		<a href="#communication-et-publicite" data-toggle="tooltip" data-placement="left" title="Stratégie et Création Publicitaire" >
			<img src="images/src/service3.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-web" data-toggle="tooltip" data-placement="left" title="Création et Réferencement des Sites Web" >
			<img src="images/src/service1.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-logiciel-progiciel" data-toggle="tooltip" data-placement="left" title="Développement de Logiciel et Progiciel" >
			<img src="images/src/service2.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#gestion-financiere-informatisee-des-entreprises" data-toggle="tooltip" data-placement="left" title="Gestion Financière Informatisée" >
			<img src="images/src/service.png" alt=""/>
		</a>
	</div>
</div>
<!-- End of Services Fixed Toggle -->

<!-- page -->
<div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row services-row"> 
            	<div class="g-column-10 ">
                	<!-- Service 1 -->
                    <div id="communication-et-publicite" class="g-row bg-text" >
                        <div class="readmoreContent ">
	                        <div class="heading-title">
	                           	<img src="images/src/home-slide-5.jpg" alt="" />
	                           	<div class="service-title">
	                                <h2>Stratégie et Création Publicitaire</h2>
	                            </div>
	                        </div>
	                        <div class="g-column-9 g-push-to-left content">
	                            <div class="entry">
	                                <p>Votre projet mérite réflexion...
									Avant toutes choses, la création commence par l'écoute et l'analyse de vos besoins.
									 Notre expertise aujourd'hui nous permet de vous amener conseils & stratégie, sur la communication de votre entreprise, qu'elle soit en projet ou datant de plusieurs dizaines d'années.</p>
									
							        <p>
							          <div class="g-row">
							          	<!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon1.png" alt="posts Title" title="posts Title">
							                            
							                        </a>
							                    </figure>
							                    <div class="posts__item__description">
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Conseil & Stratégie
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul >
							                            	<li>Audit, analyse d'image et d'opinions</li>
							                            	<li>Stratégie de communication</li>
							                            	<li>Stratégie Média / Hors Média</li>
							                            	<li>Stratégie Web</li>
							                            	<li>Stratégie de Marque</li>
							                            	<!-- <li>Achat d'espaces</li> -->
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon2.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description">
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Logo / Identité visuelle 
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Logo</li>
							                            	<li>Charte graphique complète</li>
							                            	<li>Nom de Marque</li>
							                            	<li>Pictogrammes / Signalétique</li>
							                            	<li>Série d'icônes</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon3.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    événementiel  
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Full covering adhésif</li>
							                            	<li>Street & guerilla marketing</li>
							                            	<li>Opération de Marketing direct</li>
							                            	<li>Stand BtB & BtC</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3 ">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon4.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Sur internet   
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                               	<li>Site internet vitrine</li>
							                            	<li>Site internet ecommerce</li>
							                            	<li>Site / blog d'entreprise privé</li>
							                            	<li>Interface d'administration (back office)</li>
							                            	<li>Publicité online</li>
							                            	<li>Hébergement internet</li>
							                            	<li>Dépôt de noms de domaine</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__desc