<!-- Services Fixed Toggle -->
<div class="services-toggle" >
	<div>
		<a href="#communication-et-publicite" data-toggle="tooltip" data-placement="left" title="Stratégie et Création Publicitaire" >
			<img src="images/src/service3.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-web" data-toggle="tooltip" data-placement="left" title="Création et Réferencement des Sites Web" >
			<img src="images/src/service1.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-logiciel-progiciel" data-toggle="tooltip" data-placement="left" title="Développement de Logiciel et Progiciel" >
			<img src="images/src/service2.png" alt=""/>
		</a>
	</div>
	<div>
		<a href="#gestion-financiere-informatisee-des-entreprises" data-toggle="tooltip" data-placement="left" title="Gestion Financière Informatisée" >
			<img src="images/src/service.png" alt=""/>
		</a>
	</div>
</div>
<!-- End of Services Fixed Toggle -->

<!-- page -->
<div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row services-row"> 
            	<div class="g-column-10 ">
                	<!-- Service 1 -->
                    <div id="communication-et-publicite" class="g-row bg-text" >
                        <div class="readmoreContent ">
	                        <div class="heading-title">
	                           	<img src="images/src/home-slide-5.jpg" alt="" />
	                           	<div class="service-title">
	                                <h2>Stratégie et Création Publicitaire</h2>
	                            </div>
	                        </div>
	                        <div class="g-column-9 g-push-to-left content">
	                            <div class="entry">
	                                <p>Votre projet mérite réflexion...
									Avant toute chose, la création commence par l'écoute et l'analyse de vos besoins.
									 Notre expertise aujourd'hui nous permet de vous amener conseils & stratégie, sur la communication de votre entreprise, qu'elle soit en projet ou datant de plusieurs dizaines d'années.</p>
									
							        <p>
							          <div class="g-row">
							          	<!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon1.png" alt="posts Title" title="posts Title">
							                            
							                        </a>
							                    </figure>
							                    <div class="posts__item__description">
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Conseil & Stratégie
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul >
							                            	<li>Audit, analyse d'image et d'opinions</li>
							                            	<li>Stratégie de communication</li>
							                            	<li>Stratégie Média / Hors Média</li>
							                            	<li>Stratégie Web</li>
							                            	<li>Stratégie de Marque</li>
							                            	<!-- <li>Achat d'espaces</li> -->
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon2.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description">
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Logo / Identité visuelle 
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Logo</li>
							                            	<li>Charte graphique complète</li>
							                            	<li>Nom de Marque</li>
							                            	<li>Pictogrammes / Signalétique</li>
							                            	<li>Série d'icônes</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon3.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    événementiel  
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Full covering adhésif</li>
							                            	<li>Street & guerilla marketing</li>
							                            	<li>Opération de Marketing direct</li>
							                            	<li>Stand BtB & BtC</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3 ">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon4.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Sur internet   
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                               	<li>Site internet vitrine</li>
							                            	<li>Site internet ecommerce</li>
							                            	<li>Site / blog d'entreprise privé</li>
							                            	<li>Interface d'administration (back office)</li>
							                            	<li>Publicité online</li>
							                            	<li>Hébergement internet</li>
							                            	<li>Dépôt de noms de domaine</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon5.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Sur papier   
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Carte de visite</li>
							                            	<li>Dépliant/ Plaquette commerciale</li>
							                            	<li>Affiche</li>
							                            	<li>Etiquette produit</li>
							                            	<li>Encart de publicité</li>
							                            	<li>Repiquage divers</li>
							                            	
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							            <!-- post item -->
							            <div class="g-column-3">
							                <article class="posts__item__details">
							                    <figure class="posts__item__figure g-row-3">
							                        <a class="posts__item__link">
							                            <img src="images/src/pubs-icon6.png" alt="posts Title" title="posts Title">
							                        </a>
							                    </figure>
							                    <div class="posts__item__description" >
							                        <div class="posts__item__head">
							                            <h3 class="posts__item__head__title">
							                                <a>
							                                    Applications & Développement   
							                                </a>
							                            </h3>
							                        </div>
							                        <p>
							                            <ul>
							                            	<li>Back Office internet/extranet</li>
							                            	<li>Design d'interface sur mesure</li>
							                            	<li>Développement sur mesure</li>
							                            	<li>Web application</li>
							                            	<li>Application Iphone</li>
							                            	<li>Application Androïd</li>
							                            	<li>Application Flash</li>
							                            </ul>
							                        </p>
							                    </div>
							                    <!-- posts__item__description -->
							                </article>
							                <!-- posts__item__details -->
							            </div>
							          </div>
							    	</p>
									
								</div>
	                            
	                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
	                        </div>
                        </div>
                    </div>
                    <!-- End of service 1 -->
                    <hr class="" />
                	<!-- Service 2 -->
                    <div id="developpement-web" class="g-row bg-text">
                      <div class="readmoreContent">
                        <div class="heading-title">
                            <img src="images/src/home-slide-2.jpg" alt="" />
                            <div class="service-title">
                                <h2>Création et Réferencement des Sites Web</h2>
                            </div>
                        </div>
                        <div class="g-push-to-left content">
                            <div class="entry" style="text-align: justify;">
                                <p>Le Web est devenu l’ultime référence en matière de recherche. Qu’il s’agisse de trouver un numéro de téléphone, une adresse ou simplement de se forger une opinion sur une entreprise, le réflexe premier est désormais de faire appel au Web pour répondre à nos questions.
Il est donc fort probable que vos clients se fassent une première impression de votre organisation par l’intermédiaire de votre site Web, et ce, avant même que vous ne leur parliez ou que vous ne les rencontriez. Comme la première impression est déterminante, nous considérons que l'image projetée par un site Web est primordiale dans la stratégie de développement d'une entreprise. Chez DEVMA, nous traitons minutieusement tous les aspects de la conception Web et garantissons une première impression durable.
Le design et la structure visuelle</p>
                                <p>L’attention du visiteur sera d’abord sollicitée par le visuel du site Web. Le design va bien au-delà d'un agencement de couleurs ou d'une simple disposition d'images. En effet, la conception débute par le regroupement et l'organisation des éléments. Bien que le contenu du site soit de première importance, sa présentation en est certainement l’élément névralgique puisque c’est cet aspect qui influencera la première action du visiteur: soit de poursuivre sa visite ou de quitter! Cet aspect primordial doit être considéré lors de la conception d'un design dit épuré. Le choix des teintes et des formes servira par la suite à soutenir le message véhiculé et, ainsi, assurer une uniformité pour l’ensemble du site Web.
L'ergonomie et la structure de navigation</p>
                            	<p>Une fois la première impression enrichie grâce à un design habilement ficelé, il est d’importance capitale pour l'utilisateur de trouver facilement et rapidement ce qu'il est venu chercher sur le site Web. C'est pourquoi l'ergonomie et la structure de navigation sont essentielles pour créer une expérience utilisateur de qualité. Une structure de navigation intuitive et une disposition de l'information hiérarchisée nous assurent de mettre de l'avant l'essence première du site Web, c'est-à-dire son contenu!
L'optimisation référentielle sur les moteurs de recherche (SEO)</p>
								<p>Pour qu'un site Web atteigne ses objectifs, il se doit d’offrir une expérience utilisateur de qualité, mais il doit avant tout être visible dans les moteurs de recherche pour que les gens puissent y accéder!
Le classement sur les moteurs de recherche comme Google, Yahoo et Bing est le résultat de l’influence d’un grand nombre de facteurs, et il est nécessaire d'optimiser le site Web pour le positionner face à la féroce compétition qui règne sur le Net.</p>
								<p>
									<h3 class="posts__item__head__title"><a>Le search engine optimization (SEO) se divise en 3 grandes catégories:</a></h3>
									<ol>
										<li>L'optimisation de la structure.</li>
										<li>L'optimisation du contenu.</li>
    									<li>Le profil de "backlink".</li>
    								</ol>
								</p>
								<p>Chez DEVMA, nous nous assurons que tous ces aspects soient minutieusement traités et bonifiés en fonction de vos objectifs. Nous livrons des sites optimisés et offrons des plans de maintien en continu afin que le site demeure actualisé et qu’il conserve sa valeur référentielle.
Les performances et le temps d'affichage</p>
								<p>La performance du site Web est un autre élément décisif de l'opinion que se fait un utilisateur lors d’une visite en ligne. Une fois qu’il sélectionne votre site parmi les résultats de recherche sur Google, par exemple, il est essentiel de ne pas le faire attendre pour éviter qu’il se rabatte sur un site concurrentiel. Un temps d'affichage rapide et un site réactif permettent donc à l’utilisateur de naviguer plus efficacement tout en accédant plus rapidement à l'information recherchée.
								</p>
								<h3 class="posts__item__head__title"><a>Site Web mobile (responsive)</a></h3>
								<p>Ultimement, vu le nombre grandissant d'utilisateurs mobiles, il est important de considérer qu'un pourcentage élevé de vos utilisateurs visitera votre site à partir de leur mobile. C'est pourquoi nous accordons une grande importance au développement de sites Web dits "responsive" et mobiles. Nous utilisons les technologies les plus performantes du marché et explorons sans cesse de nouvelles avenues afin d’offrir des solutions haut de gamme à la fine pointe de la technologie.</p>
                            </div>
                            
                            
                        </div>
                      </div>
                    </div>
                    <!-- End of service 2 -->
                    <hr class="" />
                    
                    <!-- Service 3 -->
                    <div id="developpement-logiciel-progiciel" class="g-row bg-text">
                      <div class="readmoreContent">
                        <div class="heading-title">
                       		<img src="images/src/home-slide-4.jpg" alt="" />
	                        <div class="service-title">
                                <h2>Développement de Logiciel et Progiciel</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                        </div>
                        <div class="g-push-to-left content">
                            <div class="entry">
                            	<p>Notre métier est de concevoir les outils dont vous et vos utilisateurs ont besoin au quotidien.</p>
                            	<p>Faisons un constat simple : toute entreprise, quelle que soit son activité ou sa taille, a besoin d’optimiser ses processus de gestion, améliorer la relation avec ses clients, gérer un stock, se doter d’outils innovants pour capter de nouveaux marchés, etc.</p>
                            	<p>Notre métier est alors de mettre à votre disposition toute notre expertise et savoir-faire pour concevoir l’application qui répond à 100% de vos besoins !</p>
                            	<p>Que ce soit une application de type « logiciel » ou « web », Devma prend en charge l’ensemble du projet : de l’étude à la maintenance, en passant par le développement, la formation des utilisateurs ou encore le suivi par un chef de projet dédié.</p>
                            	<h3 class="posts__item__head__title"><a>Notre département Conception de logiciels, d’applications et de progiciels offre les services suivants.</a></h3>
                            	<p>
                            		<ol>
                            			<li>Les applications mobiles</li>
                            			<li>Les systèmes de gestion</li>
                            			<li>Le développement de logiciels</li>
                            			<li>Les systèmes d’information d’entreprise</li>
                            			<li>Les progiciels de gestion intégrée (ERP)</li>
                            		</ol>
                            	</p>
                            </div>
                            
                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
                        </div>
                      </div>
                    </div>
                    <!-- End of service 3 -->
                    <hr class="" />
                    <!-- Service 4 -->
                    <div id="gestion-financiere-informatisee-des-entreprises" class="g-row bg-text">
                      <div class="readmoreContent">
                      	 <div class="heading-title">
                       		<img src="images/src/home-slide-3.jpg" alt="" />
	                        <div class="service-title">
                                <h2>Gestion Financière Informatisée</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                       	 </div>
                         <div class="g-push-to-left content">
                            <div class="entry">
                            	<p>Les entreprises font face à des contraintes et à des difficultés qui peuvent présenter des risques importants. L’ensemble des contraintes et des menaces dans les différents domaines, qui vont du réglementaire au droit, en palpant également les domaines techniques, normatifs ou encore sécuritaires, s’accumulent de plus en plus pour affecter les performances des entreprises et rendre le milieu de leur évolution plus complexe. Chose qui pousse les entreprises à se réorganiser, à établir une refonte des processus et mettre en point des plans d’action et des procédures correctives. Ainsi, se conformer à toutes les obligations sans affecter son niveau de performance est devenu un enjeu majeur.</p>
                            	<p>Pour gérer les multiples contraintes, associer les actions, consolider la gouvernance, et améliorer le pilotage de l’entreprise, les dirigeants doivent mettre en place une démarche d’informatisation efficace visant à améliorer la capacité et le management de leurs sociétés. De ce fait, nous disposons de hautes compétences dans le domaine de la comptabilité, le contrôle et l’audit qui pourront nous mener à une bonne gestion financière de nos clients.</p>
                            	<p>En effet, nos services seront : - Constitution de sociétés. - Conseil juridique. - Contentieux fiscal. - Études de projet. - Choix d’investissement. - Suivi comptable. - Préparation à l’audit financier.</p>
								<p>Une bonne gestion financière informatisée est un moyen de réduire l'exposition aux risques.</p>
                            </div>
                            
                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
                        </div>
                      </div>
                    </div>
                    <!-- End of service 4 -->
                    
                </div>
            </div>
        </div>
    </div>
    <!-- primary -->
</div>
<!-- page -->