<!-- Services Fixed Toggle -->
<div class="services-toggle" >
	<div>
		<a href="#communication-et-publicite" >
			<img src="http://www.itdonut.co.uk/sites/default/files/vector-with-speech-bubbles-in-form_249x249.png" width="100%" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-web" >
			<img src="http://www.itdonut.co.uk/sites/default/files/vector-with-speech-bubbles-in-form_249x249.png" width="100%" alt=""/>
		</a>
	</div>
	<div>
		<a href="#developpement-logiciel-progiciel" >
			<img src="http://www.itdonut.co.uk/sites/default/files/vector-with-speech-bubbles-in-form_249x249.png" width="100%" alt=""/>
		</a>
	</div>
	<div>
		<a href="#gestion-financiere-informatisee-des-entreprises" >
			<img src="http://www.itdonut.co.uk/sites/default/files/vector-with-speech-bubbles-in-form_249x249.png" width="100%" alt=""/>
		</a>
	</div>
</div>
<!-- End of Services Fixed Toggle -->

<!-- page -->
<div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row services-row">
            	           
                <div id="communication-et-publicite" class="g-column-12">
                	<!-- Service 1 -->
                    <div class="g-row">
                        <div class="g-column-10 offset-2 heading-title">
                            <div>
                                <h2>Stratégie et Création Publicitaire</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                        </div>
                        <!-- heading-title -->
                        <div class="g-column-4 sidebar">
			                <div class="meta">
			                	<div class="meta__author">
			                    	<figure class="">
			                        	<div class="meta__author__avatar__image">
			                            	<img src="http://www.itdonut.co.uk/sites/default/files/vector-with-speech-bubbles-in-form_249x249.png" width="100%" alt=""/>
			                            </div>
			                            <figcaption>
			                            	<!-- Written by
			                            	<b>Francisco Inchauste</b> -->
			                            </figcaption>
			                    	</figure>
			                 	</div>
			            	</div>
			            </div> 
                        <div class="g-column-6 g-push-to-left content">
                            <div class="entry">
                                <p>Votre projet mérite réflexion...
Avant toutes choses, la création commence par l'écoute et l'analyse de vos besoins. Notre expertise aujourd'hui nous permet de vous amener conseils & stratégie, sur la communication de votre entreprise, qu'elle soit en projet ou datant de plusieurs dizaines d'années.</p>
							</div>
                            
                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
                        </div>
                        
                    </div>
                    <!-- End of service 1 -->
                    <hr class="" />
                	<!-- Service 2 -->
                    <div id="developpement-web" class="g-row">
                        <div class="g-column-10 offset-2 heading-title">
                            <div>
                                <h2>Création et Réferencement des Sites Web</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                        </div>
                        <!-- heading-title -->
                        <div class="g-column-4 sidebar">
			                <div class="meta">
			                	<div class="meta__author">
			                    	<figure class="">
			                        	<div class="meta__author__avatar__image">
			                            	<img src="http://www.tuteurweb.fr/wp-content/uploads/2013/06/responsive.png" width="100%" alt=""/>
			                            </div>
			                            <figcaption>
			                            	<!-- Written by
			                            	<b>Francisco Inchauste</b> -->
			                            </figcaption>
			                    	</figure>
			                 	</div>
			            	</div>
			            </div> 
                        <div class="g-column-6 g-push-to-left content">
                            <div class="entry">
                                <p>Le Web est devenu l’ultime référence en matière de recherche. Qu’il s’agisse de trouver un numéro de téléphone, une adresse ou simplement de se forger une opinion sur une entreprise, le réflexe premier est désormais de faire appel au Web pour répondre à nos questions.
Il est donc fort probable que vos clients se fassent une première impression de votre organisation par l’intermédiaire de votre site Web, et ce, avant même que vous ne leur parliez ou que vous ne les rencontriez. Comme la première impression est déterminante, nous considérons que l'image projetée par un site Web est primordiale dans la stratégie de développement d'une entreprise. Chez DEVMA, nous traitons minutieusement tous les aspects de la conception Web et garantissons une première impression durable.
Le design et la structure visuelle</p>
                                <p>L’attention du visiteur sera d’abord sollicitée par le visuel du site Web. Le design va bien au-delà d'un agencement de couleurs ou d'une simple disposition d'images. En effet, la conception débute par le regroupement et l'organisation des éléments. Bien que le contenu du site soit de première importance, sa présentation en est certainement l’élément névralgique puisque c’est cet aspect qui influencera la première action du visiteur: soit de poursuivre sa visite ou de quitter! Cet aspect primordial doit être considéré lors de la conception d'un design dit épuré. Le choix des teintes et des formes servira par la suite à soutenir le message véhiculé et, ainsi, assurer une uniformité pour l’ensemble du site Web.
L'ergonomie et la structure de navigation</p>
                            	<p>Une fois la première impression enrichie grâce à un design habilement ficelé, il est d’importance capitale pour l'utilisateur de trouver facilement et rapidement ce qu'il est venu chercher sur le site Web. C'est pourquoi l'ergonomie et la structure de navigation sont essentielles pour créer une expérience utilisateur de qualité. Une structure de navigation intuitive et une disposition de l'information hiérarchisée nous assurent de mettre de l'avant l'essence première du site Web, c'est-à-dire son contenu!
L'optimisation référentielle sur les moteurs de recherche (SEO)</p>
								<p>Pour qu'un site Web atteigne ses objectifs, il se doit d’offrir une expérience utilisateur de qualité, mais il doit avant tout être visible dans les moteurs de recherche pour que les gens puissent y accéder!
Le classement sur les moteurs de recherche comme Google, Yahoo et Bing est le résultat de l’influence d’un grand nombre de facteurs, et il est nécessaire d'optimiser le site Web pour le positionner face à la féroce compétition qui règne sur le Net.</p>
								<p>
									<h4>Le search engine optimization (SEO) se divise en 3 grandes catégories:</h4>
									<ol>
										<li>L'optimisation de la structure.</li>
										<li>L'optimisation du contenu.</li>
    									<li>Le profil de "backlink".</li>
    								</ol>
								</p>
								<p>Chez DEVMA, nous nous assurons que tous ces aspects soient minutieusement traités et bonifiés en fonction de vos objectifs. Nous livrons des sites optimisés et offrons des plans de maintien en continu afin que le site demeure actualisé et qu’il conserve sa valeur référentielle.
Les performances et le temps d'affichage</p>
								<p>La performance du site Web est un autre élément décisif de l'opinion que se fait un utilisateur lors d’une visite en ligne. Une fois qu’il sélectionne votre site parmi les résultats de recherche sur Google, par exemple, il est essentiel de ne pas le faire attendre pour éviter qu’il se rabatte sur un site concurrentiel. Un temps d'affichage rapide et un site réactif permettent donc à l’utilisateur de naviguer plus efficacement tout en accédant plus rapidement à l'information recherchée.
								</p>
								<h4>Site Web mobile (responsive)</h4>
								<p>Ultimement, vu le nombre grandissant d'utilisateurs mobiles, il est important de considérer qu'un pourcentage élevé de vos utilisateurs visitera votre site à partir de leur mobile. C'est pourquoi nous accordons une grande importance au développement de sites Web dits "responsive" et mobiles. Nous utilisons les technologies les plus performantes du marché et explorons sans cesse de nouvelles avenues afin d’offrir des solutions haut de gamme à la fine pointe de la technologie.</p>
                            </div>
                            
                            
                        </div>
                        <!-- <div class="g-column-6 g-offset-4 g-push-to-bottom readmore-btn">
                        	<button class="button readmore-btn" style="font-size: 14px" >Lire plus...</button>
                        </div> -->
                    </div>
                    <!-- End of service 2 -->
                    <hr class="" />
                    
                    <!-- Service 3 -->
                    <div id="developpement-logiciel-progiciel" class="g-row">
                        <div class="g-column-10 offset-2 heading-title">
                            <div>
                                <h2>Développement de Logiciel et Progiciel</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                        </div>
                        <!-- heading-title -->
                        <div class="g-column-4 sidebar">
			                <div class="meta">
			                	<div class="meta__author">
			                    	<figure class="">
			                        	<div class="meta__author__avatar__image">
			                            	<img src="http://www.azapp.fr/AzappWP/wp-content/uploads/2013/11/application-sur-mesure-flexibilite.jpg" width="100%" alt=""/>
			                            </div>
			                            <figcaption>
			                            	<!-- Written by
			                            	<b>Francisco Inchauste</b> -->
			                            </figcaption>
			                    	</figure>
			                 	</div>
			            	</div>
			            </div> 
                        <div class="g-column-6 g-push-to-left content">
                            <div class="entry">
                            	<p>Notre métier est de concevoir les outils dont vous et vos utilisateurs ont besoin au quotidien.</p>
                            	<p>Faisons un constat simple : toute entreprise, quelle que soit son activité ou sa taille, a besoin d’optimiser ses processus de gestion, améliorer la relation avec ses clients, gérer un stock, se doter d’outils innovants pour capter de nouveaux marchés, etc.</p>
                            	<p>Notre métier est alors de mettre à votre disposition toute notre expertise et savoir-faire pour concevoir l’application qui répond à 100% de vos besoins !</p>
                            	<p>Que ce soit une application de type « logiciel » ou « web », Devma prend en charge l’ensemble du projet : de l’étude à la maintenance, en passant par le développement, la formation des utilisateurs ou encore le suivi par un chef de projet dédié.</p>
                            	<h4>Notre département Conception de logiciels, d’applications et de progiciels offre les services suivants.</h4>
                            	<p>
                            		<ol>
                            			<li>Les applications mobiles</li>
                            			<li>Les systèmes de gestion</li>
                            			<li>Le développement de logiciels</li>
                            			<li>Les systèmes d’information d’entreprise</li>
                            			<li>Les progiciels de gestion intégrée (ERP)</li>
                            		</ol>
                            	</p>
                            </div>
                            
                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
                        </div>
                        
                    </div>
                    <!-- End of service 3 -->
                    <hr class="" />
                    <!-- Service 4 -->
                    <div id="gestion-financiere-informatisee-des-entreprises" class="g-row">
                        <div class="g-column-10 offset-2 heading-title">
                            <div>
                                <h2>Gestion Financière Informatisée</h2>
                                <!-- <h3>13th March, 2013</h3> -->
                            </div>
                        </div>
                        <!-- heading-title -->
                        <div class="g-column-4 sidebar">
			                <div class="meta">
			                	<div class="meta__author">
			                    	<figure class="">
			                        	<div class="meta__author__avatar__image">
			                            	<img src="http://www.qualiac.com/files/qualiac/_PHOTOS_RESIZE_/ERPFluxFinanciers.jpg" width="100%" alt=""/>
			                            </div>
			                            <figcaption>
			                            	<!-- Written by
			                            	<b>Francisco Inchauste</b> -->
			                            </figcaption>
			                    	</figure>
			                 	</div>
			            	</div>
			            </div> 
                        <div class="g-column-6 g-push-to-left content">
                            <div class="entry">
                            
                            </div>
                            
                            <!-- <button class="button" style="font-size: 14px" >Lire plus...</button> -->
                        </div>
                        
                    </div>
                    <!-- End of service 4 -->
                    
                </div>
            </div>
        </div>
    </div>
    <!-- primary -->
</div>
<!-- page -->