<?php //print_r($_SERVER['REQUEST_URI']);die(); ?>
<!DOCTYPE html>
<!--[if IE 7]><html class="no-js ie ie7"><![endif]-->
<!--[if IE 8]><html class="no-js ie ie8"><![endif]-->
<!--[if IE 9]><html class="no-js ie ie9"><![endif]-->
<html class="no-js">

<head>
    <meta charset="ISO-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0, initial-scale=1" />
    <title>DEVMA - &Eacute;quipe de Professionnels Créatifs</title>
	<?= $this->headLink() ?>
    <link rel="stylesheet" href="css/common.css" media="all">
    <link rel="shortcut icon" href="images/src/favicon.png">
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


</head><body>
    <noscript>
    <div class="notice">
        <div class="notice-inner">
            <p>
                <strong>JavaScript seems to be disabled in your browser.</strong><br>
                You must have JavaScript enabled in your browser to utilize the functionality of this website.
            </p>
        </div>
    </div>
</noscript>
<!-- noscript -->
<header class="header  header_in_home">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-12 header__wrapper">
                <div class="logo">
                    <h1><a href="index-2.html" class="logo__image"><img src="images/src/logo.png" alt="" width="208px" /></a></h1>
                </div>
                <nav role="navigation" class="navigation">
                    <div class="menu">
                        <ul>
                            <li class="menu-item  current-menu-item">
                                <a href="/devma/public/">Accueil</a>
                            </li>
                            <li class="menu-item ">
                                <a href="/devma/public/presentation">Présentation</a>
                            </li>
                            <li class="menu-item menu-item_has_sub-nav ">
                                <a href="">Services</a>
                                <ul>
                                	<li><a href="#">Communication et Publicité</a></li>
                                	<li><a href="#">Développement Web</a></li>
                                    <li><a href="#">Développement de Logiciel et Progiciel</a></li>
                                    <li><a href="#">Gestion Financière Informatisée des Entreprises</a></li>   
                                </ul>
                            </li>
                            <li class="menu-item ">
                                <a href="/devma/public/contact">Contactez-nous</a>
                            </li>
                        </ul>
                    </div>
                </nav>
				<div style="clear: both"></div>
            </div>

        </div>
    </div>
</header>
<!-- header -->
<?= $this->layout()->content ?>

    <footer class="footer " role="contentinfo">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-12 footer__copyright">
                <p>&copy; Copyright 2014 <a href="http://themepile.co.uk/">DEVMA</a></p>
            </div>
            <!-- footer__copyright -->
            <div class="g-column-12 social-widget plugin-social-icons">
                <ul class="social-widget__list">
					<li class="facebook">
						<a href="#" target="_blank">Facebook</a>
					</li>
					<li class="twitter">
						<a href="#" target="_blank">Twitter</a>
					</li>
					<li class="googleplus">
						<a href="#" target="_blank">Googleplus</a>
					</li>
					<li class="linkedin">
						<a href="#" target="_blank">Linkedin</a>
					</li>
				</ul>
                <!-- social-widget__list -->
            </div>
            <!-- social-widget -->     
        </div>
    </div>
</footer>
<!-- footer -->
<div class="themepile-ui themepile-ui__back-to-top">
    <a class="themepile-ui__back-to-top__button" href="index-2.html#/top/"><span class="icon_get_arrow-top">Back To Top</span></a>
</div>
<!-- back-to-top -->
<div class="body__overlay">

</div>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
<script src="js/other/raphael.min.js"></script>
<script src="js/jquery/jquery.min.js"></script>
<script src="js/jquery/plugins/jquery.validate.js"></script>
<script src="js/jquery/plugins/jquery.countdown.js"></script>
<script src="js/jquery/plugins/jquery.tweet.js"></script>
<script src="js/jquery/plugins/jquery.easing.js"></script>
<script src="js/themepile/modules/jquery.slider.js"></script>
<script src="js/themepile/plugins/jquery.themepile.ui.accordion.js"></script>
<script src="js/themepile/plugins/jquery.themepile.ui.back-to-top.js"></script>
<script src="js/themepile/plugins/jquery.themepile.ui.alert.js"></script>
<script src="js/themepile/plugins/jquery.themepile.ui.tabs.js"></script>
<script src="js/themepile/plugins/jquery.themepile.infographic.js"></script>
<script src="js/themepile/plugins/jquery.themepile.steps-showing.js"></script>
<?= $this->headScript() ?>
<script src="js/common.js"></script></body>

</html>