<!-- header --><div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-8 g-offset-2 heading-title">
                    <div>
                        <h1>Contactez-nous</h1>
						<!-- <h3>Entrez en contact avec nous</h3> -->
                    </div>
                </div>
                <!-- heading-title -->
                <div class="g-column-8 g-offset-2 content content_align_center">
                    <div data-lng="-5.546724" data-lat="33.896735" class="map"></div>
                    <p style="font-size: 20px; line-height: 1.4; text-shadow: 0px 0px 6px black;" >
                    	15 Rue Idriss II, Apt II, Etage I, Meknes, 50000.<br>
                        Tel: +212651-745-546, +212699-045-778<br>
                        Email: <a href="index.html#">contact@devma.net</a>
                    </p>
                    <form method="post" class="form form_in_contact" >
						<!-- <h3>Send Message</h3> -->
                        <div class="form__row">
                            <input type="text" id="name" name="name" placeholder="Votre Nom *" class="required">
                        </div>
                        <div class="form__row">
                            <input type="text" id="email" name="email" placeholder="Votre Email *" class="required email">
                        </div>
                        <div class="form__row">
                            <input type="text" id="subject" name="subject" placeholder="Sujet *" class="required">
                        </div>
                        <div class="form__row">
                            <textarea id="comment" name="comment" rows="6" placeholder="Message *" class="required"></textarea>
                        </div>
                        <div class="form__row">
                            <button class="button" type="submit" style="font-size: 14px;" ><b>Envoyer Message</b></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- primary -->
    
<!-- posts -->
<!-- page -->