<!-- header --><div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-8 g-offset-2 heading-title">
                    <div>
                        <h1>Contactez-nous</h1>
						<!-- <h3>Entrez en contact avec nous</h3> -->
                    </div>
                </div>
                <!-- heading-title -->
                <div class="g-column-8 g-offset-2 content content_align_center">
                    <div data-lng="-5.546724" data-lat="33.896735" class="map"></div>
                    <p style="font-size: 24px; line-height: 1.4; text-shadow: 0px 0px 6px black;" >
                    	15 Idriss II Ave, Apt II, Floor I, Meknes, 50000.<br>
                        Tel: 200-200-2000<br>
                        Email: <a href="index.html#">ste.devma@gmail.com</a>
                    </p>
                    <form method="post" class="form form_in_contact" >
                        <h3>Send Message</h3>
                        <div class="form__row">
                            <input type="text" id="name" name="name" placeholder="Your Name *" class="required">
                        </div>
                        <div class="form__row">
                            <input type="text" id="email" name="email" placeholder="Your Email *" class="required email">
                        </div>
                        <div class="form__row">
                            <input type="text" id="subject" name="subject" placeholder="Subject *" class="required">
                        </div>
                        <div class="form__row">
                            <textarea id="comment" name="comment" rows="6" placeholder="Message *" class="required"></textarea>
                        </div>
                        <div class="form__row">
                            <button class="button" type="submit" style="font-size: 16px;" ><b>Submit Message</b></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- primary -->
    
<!-- posts -->    <div class="page__item twitter scrolled">
    <div class="l-container">
        <div class="g-row scrolled__item">
            <div class="g-column-8 g-offset-2 twitter__content">
                <a href="index.html#">
                    <span class="icon_get_twitter-alt">Twitter</span>
                </a>
                <div class="twitter__container">
                    <h3>@rpauldesign cheers - hopefully it gets across we like to have fun when we work. </h3>
                </div>

            </div>
            <div class="g-column-8 g-offset-2 twitter__follow">
                <p>You should follow us on <a href="index.html#">Twitter</a> for our latest updates.</p>
            </div>
        </div>
    </div>
</div>
<!-- twitter -->
<div class="page__item newsletter scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 g-offset-2 scrolled__item">
                <h3>Enter your email address below to receive occasional updates.</h3>
                <form method="post" action="#">
                    <input class="input" type="email" placeholder="Enter your email" name="email">
                    <button type="submit" class="button">
                        <i class="icon icon_get_arrow-size-big">Subscribe</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- newsletter --></div>
<!-- page -->