<div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-8 g-offset-2 heading-title">
                    <div>
                        <h1>PRESENTATION</h1>
                        <h3>Nous sommes une équipe de professionnels créatifs travaillant avec vous, afin de vous garantir un système de gestion meilleur.</h3>
                    </div>
                </div>
                <!-- heading-title -->
                <div class="g-column-8 g-offset-2 content">
                    <p><img src="images/src/offce.jpg" alt=""/></p>

                </div>
                <div class="g-column-8 g-offset-2 content">
                    <p>Dans un environnement économique en mutation, les entreprises font face à des difficultés de gestion de l’information. 
					De ce fait, DEVMA est au service de la réussite de ses clients de façon à faciliter les tâches et la gestion quotidienne.
					</p>
                    <p>
                        En effet, nous proposons des services visant l’augmentation de la productivité de l’entreprise et la pérennité de son patrimoine et cela
					en vous assistant de façon à bien gérer votre société et chercher comment attirer et satisfaire votre clientèle en mettant à votre
					disponibilité tout notre savoir-faire dans le domaine.
                    </p>
                </div>

            </div>
        </div>
    </div>
    <!-- primary -->


    <!-- team -->
    <div class="page__item how-we-work scrolled">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>
							Pourquoi nous choisir?
						</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                            We start by figuring out the best way to bring your ideas to life in the most creative, logical way possible.
                        </h3>
                        <p>We’ll help map your projects journey from creation to completion, through creative ideas, research and client collaboration.</p>
                    </div>
                </div>
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>Notre Objectif</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                        	Conseiller et accompagner efficacement nos clients en répondant au plus près à leurs attentes.
                        </h3>
                        <p> Pour cela nous vous proposons un vaste choix de services qui vous aidera à développé votre futur stratégie.</p>
                    </div>
                </div>
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>Mot d'Equipe</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                           	En s’appuyant sur les nouvelles technologies et les mutli-connaissances...
                        </h3>
                        <p>DEVMA met à votre disposition une équipe d'ingénieurs hautement qualifiée et dynamique qui vous accompagne dans tous vos travaux, de vos ambitions et le perfectionnement de votre service en toute sérénité et simplicité.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- how-we-work -->
<!-- <div class="page__item infographic scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-2 g-offset-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="66">
                    <span class="">  <!-- infographic__item__circle__counter ->
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Créer</h3>
            </div>
            <!-- infographic__item ->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="80">
                    <span class=""> <!-- infographic__item__circle__counter ->
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Développer</h3>
            </div>
            <!-- infographic__item ->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="78">
                    <span class=""> <!-- infographic__item__circle__counter ->
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Partager</h3>
            </div>
            <!-- infographic__item ->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="90">
                    <span class=""> <!-- infographic__item__circle__counter ->
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Explorer</h3>
            </div>
            <!-- infographic__item ->
        </div>
    </div>
</div>-->
<!-- posts -->   
<!-- projects -->    <div class="page__item testimonials scrolled">
    <div class="l-container">
        <div class="g-row">
<!--            <div class="g-column-8 g-offset-2 heading-title">
                <div>
                    <h2>Testimonials</h2>
                </div>
            </div>-->
            <!-- heading-title -->
            <div class="g-column-12 testimonials__slider scrolled__item " >
                <ul class="testimonials__list" >
                    <li class="testimonials__list__item">
                        <blockquote>
							<p>L'innovation, c'est une situation qu'on choisit parce qu'on a une passion brûlante pour quelque chose.</p>
							<cite>&ndash; Steve Jobs, Apple</cite>
						</blockquote>
						<blockquote>
							<p>Les deux choses les plus importantes n'apparaissent pas au bilan de l'entreprise : sa réputation et ses hommes.</p>
							<cite>&ndash; Henry Ford, Ford</cite>
						</blockquote>
						<blockquote>
							<p>La meilleure des publicités est un client satisfait.</p>
							<cite>&ndash; Bill Gates, Microsoft</cite>
						</blockquote>
                    </li>
                </ul>
            </div>
            <!-- testimonials__slider -->

        </div>
    </div>
</div>
<!-- testimonials --><div class="page__item newsletter scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 g-offset-2 scrolled__item">
                <h3>Enter your email address below to receive occasional updates.</h3>
                <form method="post" action="#">
                    <input class="input" type="email" placeholder="Enter your email" name="email">
                    <button type="submit" class="button">
                        <i class="icon icon_get_arrow-size-big">Subscribe</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- newsletter --></div>
<!-- page -->