<div class="page">
    <div class="primary">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-8 g-offset-2 heading-title">
                    <div>
                        <h1>DEVMA</h1>
                        <h3>Nous sommes une équipe de professionnels créatifs travaillant avec vous, afin de vous garantir un système de gestion meilleur.</h3>
                    </div>
                </div>
                <!-- heading-title -->
                <div class="g-column-8 g-offset-2 content">
                    <p><img src="images/src/offce.jpg" alt=""/></p>

                </div>
                <div class="g-column-8 g-offset-2 content">
                    <p>Dans un environnement économique en mutation, les entreprises font face à des difficultés de gestion de l’information. 
					De ce fait, DEVMA est au service de la réussite de ses clients de façon à faciliter les tâches et la gestion quotidienne.
					</p>
                    <p>
                        En effet, nous proposons des services visant l’augmentation de la productivité de l’entreprise et la pérennité de son patrimoine et cela
					en vous assistant de façon à bien gérer votre société et chercher comment attirer et satisfaire votre clientèle en mettant à votre
					disponibilité tout notre savoir-faire dans le domaine.
                    </p>
                </div>

            </div>
        </div>
    </div>
    <!-- primary -->

    <div class="page__item team scrolled">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-3 team__item scrolled__item">
                    <div class="team__item__figure">
                        <img src="images/src/team.png" alt=""/>
                    </div>
                    <div class="team__item__content">
                        <h3>Full Name</h3>
                        <p>Position</p>
                    </div>
                    <div class="team__item__controls">
                        <div class="social-widget">
                            <ul class="social-widget__list">
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_facebook">Facebook</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_twitter">Twitter</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_linkedin">Linkedin</i>
                                    </a>
                                </li>
                            </ul>
                            <!-- social-widget__list -->
                        </div>
                        <!-- social-widget -->
                    </div>
                </div>
                <div class="g-column-3 team__item scrolled__item">
                    <div class="team__item__figure">
                        <img src="images/src/team.png" alt=""/>
                    </div>
                    <div class="team__item__content">
                        <h3>Full Name</h3>
                        <p>Position</p>
                    </div>
                    <div class="team__item__controls">
                        <div class="social-widget">
                            <ul class="social-widget__list">
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_facebook">Facebook</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_twitter">Twitter</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_linkedin">Linkedin</i>
                                    </a>
                                </li>
                            </ul>
                            <!-- social-widget__list -->
                        </div>
                        <!-- social-widget -->
                    </div>
                </div>
                <div class="g-column-3 team__item scrolled__item">
                    <div class="team__item__figure">
                        <img src="images/src/team.png" alt=""/>
                    </div>
                    <div class="team__item__content">
                        <h3>Full Name</h3>
                        <p>Position</p>
                    </div>
                    <div class="team__item__controls">
                        <div class="social-widget">
                            <ul class="social-widget__list">
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_facebook">Facebook</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_twitter">Twitter</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_linkedin">Linkedin</i>
                                    </a>
                                </li>
                            </ul>
                            <!-- social-widget__list -->
                        </div>
                        <!-- social-widget -->
                    </div>
                </div>
                <div class="g-column-3 team__item scrolled__item">
                    <div class="team__item__figure">
                        <img src="images/src/team.png" alt=""/>
                    </div>
                    <div class="team__item__content">
                        <h3>Full Name</h3>
                        <p>Position</p>
                    </div>
                    <div class="team__item__controls">
                        <div class="social-widget">
                            <ul class="social-widget__list">
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_facebook">Facebook</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_twitter">Twitter</i>
                                    </a>
                                </li>
                                <li class="social-widget__list__item">
                                    <a href="index.html#" class="social-widget__list__item__link">
                                        <i class="icon icon_get_linkedin">Linkedin</i>
                                    </a>
                                </li>
                            </ul>
                            <!-- social-widget__list -->
                        </div>
                        <!-- social-widget -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- team -->
    <div class="page__item how-we-work scrolled">
        <div class="l-container">
            <div class="g-row">
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>Planning</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                            We start by figuring out the best way to bring your ideas to life in the most creative, logical way possible.
                        </h3>
                        <p>We’ll help map your projects journey from creation to completion, through creative ideas, research and client collaboration.</p>
                    </div>
                </div>
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>Design</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                            Everything we design for our clients is bespoke, created for you using years of industry experience.
                        </h3>
                        <p>We ensure your project communicates with your audience, using every last pixel to focus on delivering the right messages.</p>
                    </div>
                </div>
                <div class="g-column-4 how-we-work__item scrolled__item">
                    <div class="how-we-work__item__header">
                        <h2>Development</h2>
                    </div>
                    <div class="how-we-work__item__content">
                        <h3>
                            Using all our research, ideas and creativity, this is where we bring designs alive and start making things move.
                        </h3>
                        <p>We’ll lead the development process using the right tools and some of the best people in the industry.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- how-we-work -->
    <div class="page__item infographic scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-2 g-offset-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="66">
                    <span class="infographic__item__circle__counter">
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Skill Item</h3>
            </div>
            <!-- infographic__item -->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="80">
                    <span class="infographic__item__circle__counter">
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Skill Item</h3>
            </div>
            <!-- infographic__item -->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="78">
                    <span class="infographic__item__circle__counter">
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Skill Item</h3>
            </div>
            <!-- infographic__item -->
            <div class="g-column-2 infographic__item scrolled__item">
                <div class="infographic__item__circle" data-percent="90">
                    <span class="infographic__item__circle__counter">
                        0%
                    </span>
                </div>
                <h3 class="infographic__item__title">Skill Item</h3>
            </div>
            <!-- infographic__item -->
        </div>
    </div>
</div>
<!-- posts -->    <div class="page__item projects scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 heading-title">
                <div>
                    <h1>Notre Travail</h1>
                    <!-- <h3>Our designs not only look beautiful, they actually work. We plan with care and use years of industry experience to create everything we do.</h3> -->
					<h3>Nos conceptions non seulement belles, elles travaillent effectivement. Nous planifions avec soin et nous utilisons d'usage des années d'expérience de l'industrie pour créer tout ce que nous faisons.</h3>
                </div>
            </div>
            <!-- heading-title -->
        </div>
				<div class="g-row">
            <div class="g-column-4 projects__item projects__item_status_new scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-1.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Goethe Haus</h3>
                            </div>
                            <p>
                                Site simple creative d'une école de langues située à meknès. 
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
            <div class="g-column-4 projects__item scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-3.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Project Title</h3>
                            </div>
                            <p>
                                A clean, simple, all-about-the-work portfolio for the professional creative.
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
            <div class="g-column-4 projects__item scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-2.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Project Title</h3>
                            </div>
                            <p>
                                A clean, simple, all-about-the-work portfolio for the professional creative.
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
            <div class="g-column-4 projects__item scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-4.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Project Title</h3>
                            </div>
                            <p>
                                A clean, simple, all-about-the-work portfolio for the professional creative.
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
            <div class="g-column-4 projects__item scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-5.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Project Title</h3>
                            </div>
                            <p>
                                A clean, simple, all-about-the-work portfolio for the professional creative.
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
            <div class="g-column-4 projects__item scrolled__item">
                <a href="portfolio-post/index.html" class="projects__item__link">
                    <article class="projects__item__details">
                        <figure class="projects__item__figure">
                            <img src="images/src/project-6.jpg" alt="Project Title" title="Project Title">
                        </figure>
                        <div class="projects__item__description">
                            <div class="projects__item__head">
                                <h3 class="projects__item__head__title">Project Title</h3>
                            </div>
                            <p>
                                A clean, simple, all-about-the-work portfolio for the professional creative.
                            </p>
                        </div>
                        <!-- projects__item__description -->
                        <div class="projects__item__overlay">
                            <span>+</span>
                        </div>
                        <!-- projects__item__overlay -->
                    </article>
                    <!-- projects__item__details -->
                </a>
                <!-- projects__item__link -->
            </div>
            <!-- projects__item -->
        </div>
    
    </div>
</div>
<!-- projects -->    <div class="page__item testimonials scrolled">
    <div class="l-container">
        <div class="g-row">
<!--            <div class="g-column-8 g-offset-2 heading-title">
                <div>
                    <h2>Testimonials</h2>
                </div>
            </div>-->
            <!-- heading-title -->
            <div class="g-column-12 testimonials__slider scrolled__item">
                <ul class="testimonials__list">
                    <li class="testimonials__list__item">
                        <h3>“Imagination is the beginning of creation. You imagine what you desire,<br /> you will what you imagine, and at last, you create what you will” </h3>
                        <p> George Bernard Shaw </p>
                    </li>
                </ul>
            </div>
            <!-- testimonials__slider -->

        </div>
    </div>
</div>
<!-- testimonials --><div class="page__item newsletter scrolled">
    <div class="l-container">
        <div class="g-row">
            <div class="g-column-8 g-offset-2 scrolled__item">
                <h3>Enter your email address below to receive occasional updates.</h3>
                <form method="post" action="#">
                    <input class="input" type="email" placeholder="Enter your email" name="email">
                    <button type="submit" class="button">
                        <i class="icon icon_get_arrow-size-big">Subscribe</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- newsletter --></div>
<!-- page -->